#!/usr/bin/env bash
# =============================================================================
# devsetup.sh — Comprehensive Linux Developer Environment Bootstrap
# =============================================================================
# Supports : Debian / Ubuntu (APT) | Arch Linux (Pacman)
# Modes    : --minimal | --full | --devops | --security | --interactive
# Options  : --dry-run | --dotfiles <repo-url>
# Author   : generated by Claude
# Version  : 2.0.0
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# ─────────────────────────────────────────────────────────────────────────────
# GLOBALS & DEFAULTS
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${SCRIPT_DIR}/devsetup.log"
DOTFILES_REPO=""
DRY_RUN=false

# Install flags (all off by default; flags/interactive will enable them)
DO_MINIMAL=false
DO_FULL=false
DO_DEVOPS=false
DO_SECURITY=false
DO_GUI=false
DO_INTERACTIVE=false

REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME="$(eval echo "~${REAL_USER}")"

# ─────────────────────────────────────────────────────────────────────────────
# COLOURS
# ─────────────────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  RED='\033[0;31m';    GREEN='\033[0;32m';  YELLOW='\033[1;33m'
  BLUE='\033[0;34m';   CYAN='\033[0;36m';   BOLD='\033[1m';  RESET='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BLUE=''; CYAN=''; BOLD=''; RESET=''
fi

# ─────────────────────────────────────────────────────────────────────────────
# LOGGING HELPERS
# ─────────────────────────────────────────────────────────────────────────────
log()     { echo -e "${GREEN}[✔]${RESET} $*" | tee -a "$LOG_FILE"; }
info()    { echo -e "${BLUE}[➜]${RESET} $*" | tee -a "$LOG_FILE"; }
warn()    { echo -e "${YELLOW}[⚠]${RESET} $*" | tee -a "$LOG_FILE"; }
error()   { echo -e "${RED}[✘]${RESET} $*" | tee -a "$LOG_FILE" >&2; }
section() {
  echo "" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${CYAN}  $*${RESET}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}" | tee -a "$LOG_FILE"
}
dry()     { echo -e "${YELLOW}[DRY-RUN]${RESET} Would run: $*" | tee -a "$LOG_FILE"; }

# ─────────────────────────────────────────────────────────────────────────────
# DRY-RUN COMMAND WRAPPER
# ─────────────────────────────────────────────────────────────────────────────
run() {
  if $DRY_RUN; then
    dry "$*"
  else
    "$@" 2>&1 | tee -a "$LOG_FILE" || {
      error "Command failed: $*"
      return 1
    }
  fi
}

# ─────────────────────────────────────────────────────────────────────────────
# ERROR TRAP
# ─────────────────────────────────────────────────────────────────────────────
trap 'error "Unexpected error on line ${LINENO}. Check ${LOG_FILE} for details."; exit 1' ERR

# ─────────────────────────────────────────────────────────────────────────────
# USAGE
# ─────────────────────────────────────────────────────────────────────────────
usage() {
  cat <<EOF
${BOLD}devsetup.sh${RESET} — Linux Developer Environment Bootstrap

${BOLD}USAGE${RESET}
  sudo ./devsetup.sh [MODE] [OPTIONS]

${BOLD}MODES${RESET}
  --minimal       Core packages + languages only
  --full          Everything (languages, tools, shell, GUI, fonts)
  --devops        Core + Docker, Kubernetes, cloud CLIs
  --security      Core + hacking / security toolchain
  --interactive   Prompt for each category interactively

${BOLD}OPTIONS${RESET}
  --dry-run              Print commands without executing
  --dotfiles <repo-url>  Clone and apply your dotfiles repo
  --help                 Show this help message

${BOLD}EXAMPLES${RESET}
  sudo ./devsetup.sh --full
  sudo ./devsetup.sh --minimal --dry-run
  sudo ./devsetup.sh --devops --dotfiles https://github.com/you/dotfiles
  sudo ./devsetup.sh --interactive
EOF
  exit 0
}

# ─────────────────────────────────────────────────────────────────────────────
# ARGUMENT PARSING
# ─────────────────────────────────────────────────────────────────────────────
parse_args() {
  [[ $# -eq 0 ]] && { warn "No mode specified. Run with --help for usage."; DO_INTERACTIVE=true; return; }
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --minimal)     DO_MINIMAL=true ;;
      --full)        DO_FULL=true ;;
      --devops)      DO_DEVOPS=true ;;
      --security)    DO_SECURITY=true ;;
      --interactive) DO_INTERACTIVE=true ;;
      --dry-run)     DRY_RUN=true; warn "DRY-RUN mode enabled — no changes will be made." ;;
      --dotfiles)    shift; DOTFILES_REPO="$1" ;;
      --help|-h)     usage ;;
      *) error "Unknown argument: $1"; usage ;;
    esac
    shift
  done
}

# ─────────────────────────────────────────────────────────────────────────────
# OS DETECTION
# ─────────────────────────────────────────────────────────────────────────────
detect_os() {
  section "Detecting Operating System"

  if [[ -f /etc/os-release ]]; then
    source /etc/os-release
    OS_ID="${ID,,}"       # lowercase
    OS_LIKE="${ID_LIKE,,:-}"
  else
    error "/etc/os-release not found. Cannot detect OS."
    exit 1
  fi

  if [[ "$OS_ID" == "arch" || "$OS_LIKE" == *"arch"* ]]; then
    PKG_MANAGER="pacman"
    PKG_INSTALL="pacman -S --needed --noconfirm"
    PKG_UPDATE="pacman -Syu --noconfirm"
    log "Detected: Arch Linux (pacman)"
  elif [[ "$OS_ID" == "ubuntu" || "$OS_ID" == "debian" || "$OS_LIKE" == *"debian"* || "$OS_LIKE" == *"ubuntu"* ]]; then
    PKG_MANAGER="apt"
    PKG_INSTALL="apt-get install -y"
    PKG_UPDATE="apt-get update && apt-get upgrade -y"
    log "Detected: Debian/Ubuntu (apt)"
  else
    error "Unsupported OS: $OS_ID. Only Arch and Debian/Ubuntu are supported."
    exit 1
  fi

  export PKG_MANAGER PKG_INSTALL PKG_UPDATE OS_ID OS_LIKE
}

# ─────────────────────────────────────────────────────────────────────────────
# ROOT CHECK
# ─────────────────────────────────────────────────────────────────────────────
check_root() {
  if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root (use sudo)."
    exit 1
  fi
  info "Running as root. Real user: ${REAL_USER} (home: ${REAL_HOME})"
}

# ─────────────────────────────────────────────────────────────────────────────
# HELPER: run command as real (non-root) user
# ─────────────────────────────────────────────────────────────────────────────
as_user() {
  if $DRY_RUN; then
    dry "sudo -u ${REAL_USER} $*"
  else
    sudo -u "${REAL_USER}" "$@" 2>&1 | tee -a "$LOG_FILE"
  fi
}

# ─────────────────────────────────────────────────────────────────────────────
# HELPER: check if a command exists
# ─────────────────────────────────────────────────────────────────────────────
has_cmd() { command -v "$1" &>/dev/null; }

# ─────────────────────────────────────────────────────────────────────────────
# HELPER: append line to file if not already present (idempotent)
# ─────────────────────────────────────────────────────────────────────────────
append_if_missing() {
  local line="$1"
  local file="$2"
  if ! grep -qxF "$line" "$file" 2>/dev/null; then
    echo "$line" >> "$file"
  fi
}

# ─────────────────────────────────────────────────────────────────────────────
# INTERACTIVE MODE
# ─────────────────────────────────────────────────────────────────────────────
interactive_mode() {
  section "Interactive Setup"
  echo -e "${BOLD}What would you like to install? (y/n for each)${RESET}\n"

  ask() {
    local prompt="$1"
    local var="$2"
    read -rp "$(echo -e "  ${CYAN}${prompt}${RESET} [y/N] ")" ans
    [[ "${ans,,}" == "y" ]] && eval "$var=true"
  }

  ask "Core tools (git, curl, build tools, neovim, fzf, ripgrep)" "DO_MINIMAL"
  ask "Programming languages (Node, Python, Rust, Go, Java, .NET)" "INSTALL_LANGS"
  ask "DevOps tools (Docker, kubectl, terraform, cloud CLIs)"       "DO_DEVOPS"
  ask "Security / hacking tools (nmap, wireshark, hashcat, gobuster)" "DO_SECURITY"
  ask "Shell setup (zsh + oh-my-zsh + starship)"                   "INSTALL_SHELL"
  ask "CLI enhancements (bat, eza, httpie, tmux)"                   "INSTALL_CLI"
  ask "GUI apps (VS Code, Brave, flameshot, copyq)"                 "DO_GUI"
  ask "Bangla input (ibus-avro)"                                    "INSTALL_IBUS"
  ask "Flatpak + Flathub"                                           "INSTALL_FLATPAK"

  read -rp "$(echo -e "  ${CYAN}Dotfiles repo URL (leave empty to skip):${RESET} ")" DOTFILES_REPO
  export INSTALL_LANGS INSTALL_SHELL INSTALL_CLI INSTALL_IBUS INSTALL_FLATPAK
}

# =============================================================================
# ███████╗███████╗████████╗██╗   ██╗██████╗
# ██╔════╝██╔════╝╚══██╔══╝██║   ██║██╔══██╗
# ███████╗█████╗     ██║   ██║   ██║██████╔╝
# ╚════██║██╔══╝     ██║   ██║   ██║██╔═══╝
# ███████║███████╗   ██║   ╚██████╔╝██║
# ╚══════╝╚══════╝   ╚═╝    ╚═════╝ ╚═╝  FUNCTIONS
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# 1. SYSTEM UPDATE
# ─────────────────────────────────────────────────────────────────────────────
update_system() {
  section "Updating System Packages"
  if [[ "$PKG_MANAGER" == "apt" ]]; then
    run apt-get update
    run apt-get upgrade -y
    run apt-get install -y software-properties-common apt-transport-https \
        ca-certificates gnupg lsb-release
  else
    run pacman -Syu --noconfirm
    # Install yay AUR helper if missing
    if ! has_cmd yay; then
      info "Installing yay (AUR helper)..."
      run pacman -S --needed --noconfirm base-devel git
      TMP_YAY=$(mktemp -d)
      run git clone https://aur.archlinux.org/yay.git "$TMP_YAY/yay"
      cd "$TMP_YAY/yay" && as_user makepkg -si --noconfirm
      cd "$SCRIPT_DIR"
      rm -rf "$TMP_YAY"
    fi
  fi
  log "System update complete."
}

# ─────────────────────────────────────────────────────────────────────────────
# 2. CORE PACKAGES
# ─────────────────────────────────────────────────────────────────────────────
install_core() {
  section "Installing Core Packages"

  local APT_PKGS=(
    git curl wget unzip zip tar xz-utils
    build-essential cmake pkg-config
    htop btop tree file
    ripgrep fd-find fzf
    neovim tmux zsh
    net-tools dnsutils traceroute
    jq yq
    fonts-firacode
  )

  local PACMAN_PKGS=(
    git curl wget unzip zip tar xz
    base-devel cmake pkgconf
    htop btop tree file
    ripgrep fd fzf
    neovim tmux zsh
    net-tools bind-tools traceroute
    jq yq
    ttf-fira-code
  )

  if [[ "$PKG_MANAGER" == "apt" ]]; then
    run apt-get install -y "${APT_PKGS[@]}"
    # fd-find ships as 'fdfind' on Debian/Ubuntu — symlink to 'fd'
    if has_cmd fdfind && ! has_cmd fd; then
      run ln -sf "$(command -v fdfind)" /usr/local/bin/fd
    fi
  else
    run pacman -S --needed --noconfirm "${PACMAN_PKGS[@]}"
  fi

  log "Core packages installed."
}

# ─────────────────────────────────────────────────────────────────────────────
# 3. PROGRAMMING LANGUAGES
# ─────────────────────────────────────────────────────────────────────────────
install_languages() {
  section "Installing Programming Languages"

  # ── C / C++ ──────────────────────────────────────────────────────────────
  info "C/C++ toolchain..."
  if [[ "$PKG_MANAGER" == "apt" ]]; then
    run apt-get install -y gcc g++ clang clang-format clang-tidy lldb gdb valgrind
  else
    run pacman -S --needed --noconfirm gcc clang lldb gdb valgrind
  fi
  log "C/C++ installed."

  # ── Java (OpenJDK) ───────────────────────────────────────────────────────
  info "Java (OpenJDK)..."
  if [[ "$PKG_MANAGER" == "apt" ]]; then
    run apt-get install -y default-jdk maven gradle
  else
    run pacman -S --needed --noconfirm jdk-openjdk maven gradle
  fi
  log "Java installed: $(java -version 2>&1 | head -1 || echo 'see log')"

  # ── Python ───────────────────────────────────────────────────────────────
  info "Python 3 + pip + pipx + venv..."
  if [[ "$PKG_MANAGER" == "apt" ]]; then
    run apt-get install -y python3 python3-pip python3-venv python3-dev pipx
  else
    run pacman -S --needed --noconfirm python python-pip python-pipx
  fi
  # Ensure pipx path
  as_user pipx ensurepath 2>/dev/null || true
  log "Python installed: $(python3 --version 2>/dev/null || echo 'see log')"

  # ── Node.js via nvm ──────────────────────────────────────────────────────
  info "Node.js via nvm..."
  if [[ ! -d "${REAL_HOME}/.nvm" ]]; then
    NVM_LATEST=$(curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest \
                 | grep '"tag_name"' | cut -d'"' -f4)
    run as_user bash -c \
      "curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_LATEST}/install.sh | bash"
    log "nvm ${NVM_LATEST} installed."
  else
    log "nvm already installed — skipping."
  fi
  # Install LTS Node inside nvm
  as_user bash -c \
    'export NVM_DIR="$HOME/.nvm"; source "$NVM_DIR/nvm.sh"; nvm install --lts; nvm alias default lts/*' \
    || warn "Node LTS install via nvm encountered an issue — check log."
  log "Node.js LTS installed."

  # ── Bun ──────────────────────────────────────────────────────────────────
  info "Bun..."
  if ! as_user bash -c 'command -v bun &>/dev/null'; then
    run as_user bash -c 'curl -fsSL https://bun.sh/install | bash'
    log "Bun installed."
  else
    log "Bun already installed — skipping."
  fi

  # ── Rust via rustup ──────────────────────────────────────────────────────
  info "Rust via rustup..."
  if ! as_user bash -c 'command -v rustup &>/dev/null'; then
    run as_user bash -c \
      'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path'
    log "Rust installed."
  else
    run as_user bash -c 'source "$HOME/.cargo/env"; rustup update'
    log "Rust updated."
  fi

  # ── Go ───────────────────────────────────────────────────────────────────
  info "Go (latest)..."
  if ! has_cmd go; then
    GO_VER=$(curl -s https://go.dev/dl/?mode=json | grep -o '"version":"go[^"]*"' | head -1 | cut -d'"' -f4)
    GO_ARCH="linux-amd64"
    run curl -fsSL "https://go.dev/dl/${GO_VER}.${GO_ARCH}.tar.gz" -o /tmp/go.tar.gz
    run tar -C /usr/local -xzf /tmp/go.tar.gz
    rm -f /tmp/go.tar.gz
    # Add to system profile
    cat > /etc/profile.d/go.sh <<'EOF'
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
EOF
    log "Go ${GO_VER} installed."
  else
    log "Go already installed: $(go version 2>/dev/null || echo 'see log')"
  fi

  # ── .NET SDK ─────────────────────────────────────────────────────────────
  info ".NET SDK..."
  if ! has_cmd dotnet; then
    if [[ "$PKG_MANAGER" == "apt" ]]; then
      # Microsoft feed
      DISTRO_VER=$(lsb_release -rs 2>/dev/null || echo "22.04")
      run curl -fsSL "https://packages.microsoft.com/config/ubuntu/${DISTRO_VER}/packages-microsoft-prod.deb" \
          -o /tmp/packages-microsoft-prod.deb
      run dpkg -i /tmp/packages-microsoft-prod.deb
      rm -f /tmp/packages-microsoft-prod.deb
      run apt-get update
      run apt-get install -y dotnet-sdk-8.0 dotnet-sdk-6.0   # latest stable + LTS
    else
      run pacman -S --needed --noconfirm dotnet-sdk
    fi
    log ".NET SDK installed: $(dotnet --version 2>/dev/null || echo 'see log')"
  else
    log ".NET already installed — skipping."
  fi
}

# ─────────────────────────────────────────────────────────────────────────────
# 4. SHELL & TERMINAL
# ─────────────────────────────────────────────────────────────────────────────
install_shell() {
  section "Shell Setup — Zsh + Oh-My-Zsh + Starship"

  # ── Zsh default shell ────────────────────────────────────────────────────
  local ZSH_PATH
  ZSH_PATH=$(command -v zsh || echo "")
  if [[ -z "$ZSH_PATH" ]]; then
    if [[ "$PKG_MANAGER" == "apt" ]]; then run apt-get install -y zsh
    else run pacman -S --needed --noconfirm zsh; fi
    ZSH_PATH=$(command -v zsh)
  fi

  # Append to /etc/shells if needed
  grep -qxF "$ZSH_PATH" /etc/shells || echo "$ZSH_PATH" >> /etc/shells

  if [[ "$(getent passwd "${REAL_USER}" | cut -d: -f7)" != "$ZSH_PATH" ]]; then
    run chsh -s "$ZSH_PATH" "${REAL_USER}"
    log "Default shell set to zsh for ${REAL_USER}."
  else
    log "zsh already default shell."
  fi

  # ── Oh-My-Zsh ─────────────────────────────────────────────────────────
  local OMZ_DIR="${REAL_HOME}/.oh-my-zsh"
  if [[ ! -d "$OMZ_DIR" ]]; then
    run as_user bash -c \
      'RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
    log "Oh-My-Zsh installed."
  else
    log "Oh-My-Zsh already installed — skipping."
  fi

  # ── zsh plugins ───────────────────────────────────────────────────────
  local ZSH_CUSTOM="${OMZ_DIR}/custom"

  # zsh-autosuggestions
  if [[ ! -d "${ZSH_CUSTOM}/plugins/zsh-autosuggestions" ]]; then
    run as_user git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions \
        "${ZSH_CUSTOM}/plugins/zsh-autosuggestions"
    log "zsh-autosuggestions installed."
  fi

  # zsh-syntax-highlighting
  if [[ ! -d "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting" ]]; then
    run as_user git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting \
        "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting"
    log "zsh-syntax-highlighting installed."
  fi

  # ── Starship prompt ───────────────────────────────────────────────────
  if ! has_cmd starship; then
    run bash -c 'curl -sS https://starship.rs/install.sh | sh -s -- -y'
    log "Starship prompt installed."
  else
    log "Starship already installed."
  fi

  configure_zshrc
}

configure_zshrc() {
  local ZSHRC="${REAL_HOME}/.zshrc"

  # Back up existing .zshrc
  [[ -f "$ZSHRC" ]] && ! $DRY_RUN && cp "$ZSHRC" "${ZSHRC}.bak.$(date +%Y%m%d%H%M%S)"

  if $DRY_RUN; then
    dry "Would write ${ZSHRC}"
    return
  fi

  # Write full .zshrc
  cat > "$ZSHRC" <<'ZSHRC_EOF'
# ── Oh-My-Zsh ──────────────────────────────────────────────────────────────
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""    # Using Starship instead

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  docker
  kubectl
  python
  node
  rust
  golang
  fzf
  z
)

source "$ZSH/oh-my-zsh.sh"

# ── Starship ───────────────────────────────────────────────────────────────
eval "$(starship init zsh)"

# ── NVM ────────────────────────────────────────────────────────────────────
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"

# ── Rust / Cargo ───────────────────────────────────────────────────────────
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

# ── Go ─────────────────────────────────────────────────────────────────────
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"

# ── Bun ────────────────────────────────────────────────────────────────────
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# ── pipx ───────────────────────────────────────────────────────────────────
export PATH="$HOME/.local/bin:$PATH"

# ── Aliases ────────────────────────────────────────────────────────────────
alias ls='eza --icons --group-directories-first'
alias ll='eza -alh --icons --group-directories-first'
alias lt='eza --tree --level=2 --icons'
alias cat='bat --paging=never'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias cls='clear'
alias vim='nvim'
alias vi='nvim'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'
alias gd='git diff'

# Docker aliases
alias dps='docker ps'
alias dimg='docker images'
alias dex='docker exec -it'
alias dlogs='docker logs -f'
alias dprune='docker system prune -af'

# Safety nets
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# ── FZF ────────────────────────────────────────────────────────────────────
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'

# ── Editor ─────────────────────────────────────────────────────────────────
export EDITOR='nvim'
export VISUAL='nvim'
ZSHRC_EOF

  chown "${REAL_USER}:${REAL_USER}" "$ZSHRC"
  log ".zshrc configured."
}

# ─────────────────────────────────────────────────────────────────────────────
# 5. CLI ENHANCEMENTS
# ─────────────────────────────────────────────────────────────────────────────
install_cli_tools() {
  section "CLI Enhancements"

  if [[ "$PKG_MANAGER" == "apt" ]]; then
    run apt-get install -y bat httpie tmux zellij 2>/dev/null || true
    # bat ships as 'batcat' on Debian/Ubuntu — symlink
    if has_cmd batcat && ! has_cmd bat; then
      run ln -sf "$(command -v batcat)" /usr/local/bin/bat
    fi
    # eza via cargo (not in apt repos reliably) or github release
    if ! has_cmd eza; then
      info "Installing eza via cargo..."
      as_user bash -c 'source "$HOME/.cargo/env" && cargo install eza' || \
        warn "eza install failed — you can install manually later."
    fi
  else
    run pacman -S --needed --noconfirm bat httpie tmux zellij eza
  fi

  # zellij (if not installed via pkg manager)
  if ! has_cmd zellij; then
    as_user bash -c 'bash <(curl -fsSL https://zellij.dev/launch) --version latest' || true
  fi

  log "CLI tools installed."
}

# ─────────────────────────────────────────────────────────────────────────────
# 6. GIT CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
configure_git() {
  section "Git Configuration"

  local GIT_NAME GIT_EMAIL
  GIT_NAME=$(as_user git config --global user.name 2>/dev/null || echo "")
  GIT_EMAIL=$(as_user git config --global user.email 2>/dev/null || echo "")

  if [[ -z "$GIT_NAME" ]]; then
    if $DRY_RUN; then
      dry "Would prompt for git user name"
    else
      read -rp "$(echo -e "  ${CYAN}Enter your git user.name:${RESET} ")" GIT_NAME
      as_user git config --global user.name "$GIT_NAME"
    fi
  else
    log "Git name already set: $GIT_NAME"
  fi

  if [[ -z "$GIT_EMAIL" ]]; then
    if $DRY_RUN; then
      dry "Would prompt for git user email"
    else
      read -rp "$(echo -e "  ${CYAN}Enter your git user.email:${RESET} ")" GIT_EMAIL
      as_user git config --global user.email "$GIT_EMAIL"
    fi
  else
    log "Git email already set: $GIT_EMAIL"
  fi

  if ! $DRY_RUN; then
    # Sensible global git defaults
    as_user git config --global core.editor "nvim"
    as_user git config --global init.defaultBranch "main"
    as_user git config --global pull.rebase false
    as_user git config --global color.ui auto
    as_user git config --global core.autocrlf input
    as_user git config --global alias.lg "log --oneline --graph --decorate --all"
  fi

  log "Git configured."
}

# ─────────────────────────────────────────────────────────────────────────────
# 7. SSH KEY SETUP
# ─────────────────────────────────────────────────────────────────────────────
setup_ssh() {
  section "SSH Key Setup"

  local SSH_DIR="${REAL_HOME}/.ssh"
  local KEY_FILE="${SSH_DIR}/id_ed25519"

  if $DRY_RUN; then
    dry "Would create SSH key at ${KEY_FILE} if missing"
    return
  fi

  as_user mkdir -p "$SSH_DIR"
  chmod 700 "$SSH_DIR"

  if [[ ! -f "$KEY_FILE" ]]; then
    local GIT_EMAIL
    GIT_EMAIL=$(as_user git config --global user.email 2>/dev/null || echo "${REAL_USER}@$(hostname)")
    run as_user ssh-keygen -t ed25519 -C "$GIT_EMAIL" -f "$KEY_FILE" -N ""
    log "SSH key generated: ${KEY_FILE}.pub"
    echo ""
    info "Your public key (add to GitHub/GitLab):"
    echo -e "${CYAN}$(cat "${KEY_FILE}.pub")${RESET}"
    echo ""
  else
    log "SSH key already exists at ${KEY_FILE} — skipping."
  fi

  # Start ssh-agent on login via .zshrc
  append_if_missing 'eval "$(ssh-agent -s)" > /dev/null 2>&1' "${REAL_HOME}/.zshrc"
  append_if_missing 'ssh-add ~/.ssh/id_ed25519 2>/dev/null' "${REAL_HOME}/.zshrc"
}

# ─────────────────────────────────────────────────────────────────────────────
# 8. EDITORS (VS Code)
# ─────────────────────────────────────────────────────────────────────────────
install_editors() {
  section "Editors — VS Code"

  if has_cmd code; then
    log "VS Code already installed — skipping."
  else
    if [[ "$PKG_MANAGER" == "apt" ]]; then
      run curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
          | gpg --dearmor -o /usr/share/keyrings/microsoft-archive-keyring.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] \
https://packages.microsoft.com/repos/vscode stable main" \
          > /etc/apt/sources.list.d/vscode.list
      run apt-get update
      run apt-get install -y code
    else
      # Arch: VS Code is in AUR
      as_user yay -S --needed --noconfirm visual-studio-code-bin || \
        warn "VS Code AUR install failed — try manually."
    fi
    log "VS Code installed."
  fi

  # ── VS Code Extensions ─────────────────────────────────────────────────
  if has_cmd code; then
    local EXTENSIONS=(
      ms-vscode.cpptools
      ms-python.python
      ms-python.vscode-pylance
      ms-azuretools.vscode-docker
      eamodio.gitlens
      esbenp.prettier-vscode
      rust-lang.rust-analyzer
      golang.go
      ms-dotnettools.csharp
      redhat.java
      bradlc.vscode-tailwindcss
      dbaeumer.vscode-eslint
      ritwickdey.liveserver
      vscodevim.vim
      catppuccin.catppuccin-vsc
    )
    info "Installing VS Code extensions..."
    for ext in "${EXTENSIONS[@]}"; do
      as_user code --install-extension "$ext" --force 2>/dev/null \
        && log "  Extension: $ext" \
        || warn "  Failed to install extension: $ext"
    done
  fi
}

# ─────────────────────────────────────────────────────────────────────────────
# 9. DEVOPS TOOLS
# ─────────────────────────────────────────────────────────────────────────────
install_devops() {
  section "DevOps Tools"

  # ── Docker ────────────────────────────────────────────────────────────
  info "Docker..."
  if ! has_cmd docker; then
    if [[ "$PKG_MANAGER" == "apt" ]]; then
      run curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
          | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
          > /etc/apt/sources.list.d/docker.list
      run apt-get update
      run apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    else
      run pacman -S --needed --noconfirm docker docker-compose
    fi
    run systemctl enable --now docker
    run usermod -aG docker "${REAL_USER}"
    log "Docker installed. Re-login or run 'newgrp docker' to use without sudo."
  else
    log "Docker already installed."
  fi

  # ── kubectl ──────────────────────────────────────────────────────────
  info "kubectl..."
  if ! has_cmd kubectl; then
    run curl -fsSL "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
        -o /usr/local/bin/kubectl
    run chmod +x /usr/local/bin/kubectl
    log "kubectl installed."
  else
    log "kubectl already installed."
  fi

  # ── Helm ────────────────────────────────────────────────────────────
  info "Helm..."
  if ! has_cmd helm; then
    run bash -c 'curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash'
    log "Helm installed."
  else
    log "Helm already installed."
  fi

  # ── Terraform ────────────────────────────────────────────────────────
  info "Terraform..."
  if ! has_cmd terraform; then
    if [[ "$PKG_MANAGER" == "apt" ]]; then
      run curl -fsSL https://apt.releases.hashicorp.com/gpg \
          | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
          > /etc/apt/sources.list.d/hashicorp.list
      run apt-get update
      run apt-get install -y terraform
    else
      as_user yay -S --needed --noconfirm terraform || \
        warn "terraform AUR install failed."
    fi
    log "Terraform installed."
  else
    log "Terraform already installed."
  fi

  # ── AWS CLI ──────────────────────────────────────────────────────────
  info "AWS CLI v2..."
  if ! has_cmd aws; then
    run curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
    run unzip -q /tmp/awscliv2.zip -d /tmp/awscli
    run /tmp/awscli/aws/install
    rm -rf /tmp/awscli /tmp/awscliv2.zip
    log "AWS CLI installed."
  else
    log "AWS CLI already installed."
  fi

  # ── cloudflared ──────────────────────────────────────────────────────
  info "cloudflared..."
  if ! has_cmd cloudflared; then
    run curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
        -o /usr/local/bin/cloudflared
    run chmod +x /usr/local/bin/cloudflared
    log "cloudflared installed."
  else
    log "cloudflared already installed."
  fi

  log "DevOps tools installed."
}

# ─────────────────────────────────────────────────────────────────────────────
# 10. SECURITY / HACKING TOOLS
# ─────────────────────────────────────────────────────────────────────────────
install_security() {
  section "Security / Hacking Tools"

  local APT_SEC_PKGS=(
    nmap wireshark-qt
    john hashcat
    aircrack-ng
    sqlmap
    dirb gobuster feroxbuster
    netcat-openbsd socat
    binutils gdb strace ltrace
    exiftool steghide
    python3-pwntools
  )

  local PAC_SEC_PKGS=(
    nmap wireshark-qt
    john hashcat
    aircrack-ng
    sqlmap
    gobuster
    netcat socat
    binutils gdb strace ltrace
    perl-image-exiftool steghide
  )

  if [[ "$PKG_MANAGER" == "apt" ]]; then
    # Add Kali/parrot repo for hacking tools on Ubuntu (optional)
    run apt-get install -y "${APT_SEC_PKGS[@]}" 2>/dev/null || \
      warn "Some security packages may not be available on this distro."
  else
    run pacman -S --needed --noconfirm "${PAC_SEC_PKGS[@]}" 2>/dev/null || \
      warn "Some security packages unavailable."
    as_user yay -S --needed --noconfirm gobuster feroxbuster 2>/dev/null || true
  fi

  # ── pwndbg (enhanced GDB) ─────────────────────────────────────────────
  if [[ ! -d "${REAL_HOME}/pwndbg" ]]; then
    run as_user git clone --depth 1 https://github.com/pwndbg/pwndbg \
        "${REAL_HOME}/pwndbg"
    run bash "${REAL_HOME}/pwndbg/setup.sh" || warn "pwndbg setup failed."
    log "pwndbg installed."
  else
    log "pwndbg already present."
  fi

  # ── Burp Suite Community (via curl) ─────────────────────────────────
  info "To install Burp Suite Community: https://portswigger.net/burp/releases"
  info "To install Metasploit: https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html"

  log "Security tools installed."
}

# ─────────────────────────────────────────────────────────────────────────────
# 11. GUI APPLICATIONS
# ─────────────────────────────────────────────────────────────────────────────
install_gui_apps() {
  section "GUI Applications"

  # ── Brave Browser ─────────────────────────────────────────────────────
  if ! has_cmd brave-browser && ! has_cmd brave; then
    if [[ "$PKG_MANAGER" == "apt" ]]; then
      run curl -fsSL https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg \
          | gpg --dearmor -o /usr/share/keyrings/brave-browser-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] \
https://brave-browser-apt-release.s3.brave.com/ stable main" \
          > /etc/apt/sources.list.d/brave-browser-release.list
      run apt-get update
      run apt-get install -y brave-browser
    else
      as_user yay -S --needed --noconfirm brave-bin || warn "Brave AUR install failed."
    fi
    log "Brave browser installed."
  else
    log "Brave already installed."
  fi

  # ── Flameshot (screenshot tool) ───────────────────────────────────────
  if ! has_cmd flameshot; then
    [[ "$PKG_MANAGER" == "apt" ]] \
      && run apt-get install -y flameshot \
      || run pacman -S --needed --noconfirm flameshot
    log "Flameshot installed."
  fi

  # ── CopyQ (clipboard manager) ─────────────────────────────────────────
  if ! has_cmd copyq; then
    [[ "$PKG_MANAGER" == "apt" ]] \
      && run apt-get install -y copyq \
      || run pacman -S --needed --noconfirm copyq
    log "CopyQ installed."
  fi

  log "GUI apps installed."
}

# ─────────────────────────────────────────────────────────────────────────────
# 12. IBUS BANGLA INPUT
# ─────────────────────────────────────────────────────────────────────────────
install_ibus() {
  section "iBus Bangla Input (ibus-avro)"

  if [[ "$PKG_MANAGER" == "apt" ]]; then
    run apt-get install -y ibus ibus-avro
  else
    run pacman -S --needed --noconfirm ibus
    as_user yay -S --needed --noconfirm ibus-avro || warn "ibus-avro not found in AUR."
  fi

  # Add iBus env vars to .zshrc
  local IBUS_BLOCK="
# ── iBus ────────────────────────────────────────────────────────────────────
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
"
  if ! grep -q "GTK_IM_MODULE=ibus" "${REAL_HOME}/.zshrc" 2>/dev/null; then
    $DRY_RUN || echo "$IBUS_BLOCK" >> "${REAL_HOME}/.zshrc"
  fi

  log "iBus + ibus-avro installed. Run 'ibus-setup' to configure."
}

# ─────────────────────────────────────────────────────────────────────────────
# 13. FLATPAK
# ─────────────────────────────────────────────────────────────────────────────
install_flatpak() {
  section "Flatpak + Flathub"

  if ! has_cmd flatpak; then
    [[ "$PKG_MANAGER" == "apt" ]] \
      && run apt-get install -y flatpak \
      || run pacman -S --needed --noconfirm flatpak
  fi

  # Add Flathub remote (idempotent)
  run flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo || true

  # Optional Flatpak apps
  local FLATPAK_APPS=(
    com.spotify.Client
    org.videolan.VLC
    com.obsproject.Studio
    org.gimp.GIMP
  )

  info "Installing optional Flatpak apps..."
  for app in "${FLATPAK_APPS[@]}"; do
    run flatpak install -y --noninteractive flathub "$app" 2>/dev/null \
      && log "  Flatpak: $app" \
      || warn "  Could not install $app"
  done
}

# ─────────────────────────────────────────────────────────────────────────────
# 14. DOTFILES
# ─────────────────────────────────────────────────────────────────────────────
setup_dotfiles() {
  section "Dotfiles Setup"

  if [[ -z "$DOTFILES_REPO" ]]; then
    info "No dotfiles repo provided — skipping."
    return
  fi

  local DOTFILES_DIR="${REAL_HOME}/.dotfiles"

  if [[ -d "$DOTFILES_DIR" ]]; then
    info "Dotfiles repo already cloned. Pulling latest..."
    run as_user git -C "$DOTFILES_DIR" pull
  else
    run as_user git clone "$DOTFILES_REPO" "$DOTFILES_DIR"
  fi

  # Run install script if present
  for installer in \
    "${DOTFILES_DIR}/install.sh" \
    "${DOTFILES_DIR}/setup.sh" \
    "${DOTFILES_DIR}/bootstrap.sh"
  do
    if [[ -f "$installer" ]]; then
      info "Running dotfiles installer: $installer"
      run as_user bash "$installer"
      break
    fi
  done

  # Fallback: symlink common dotfiles
  local DOT_FILES=(.zshrc .bashrc .vimrc .gitconfig .tmux.conf .config/nvim)
  for f in "${DOT_FILES[@]}"; do
    local src="${DOTFILES_DIR}/${f}"
    local dst="${REAL_HOME}/${f}"
    if [[ -e "$src" ]] && [[ ! -L "$dst" ]]; then
      mkdir -p "$(dirname "$dst")"
      run as_user ln -sf "$src" "$dst"
      log "  Symlinked: $f"
    fi
  done

  log "Dotfiles applied."
}

# ─────────────────────────────────────────────────────────────────────────────
# 15. NETWORKING TOOLS
# ─────────────────────────────────────────────────────────────────────────────
install_networking() {
  section "Networking Tools"

  local APT_NET=(curl wget httpie net-tools dnsutils traceroute ncat)
  local PAC_NET=(curl wget python-httpie net-tools bind-tools traceroute ncat)

  if [[ "$PKG_MANAGER" == "apt" ]]; then
    run apt-get install -y "${APT_NET[@]}"
  else
    run pacman -S --needed --noconfirm "${PAC_NET[@]}"
  fi

  log "Networking tools installed."
}

# ─────────────────────────────────────────────────────────────────────────────
# 16. FINAL SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
print_summary() {
  section "Setup Complete 🎉"
  echo ""
  echo -e "${BOLD}Installed / Configured:${RESET}"

  local items=(
    "git"           "curl"      "neovim"    "fzf"
    "ripgrep"       "fd"        "zsh"       "starship"
    "bat"           "eza"       "tmux"
    "python3"       "node"      "bun"       "rustup"
    "go"            "dotnet"    "java"      "gcc"
  )
  $DO_DEVOPS || $DO_FULL && items+=("docker" "kubectl" "helm" "terraform" "aws")
  $DO_SECURITY || $DO_FULL && items+=("nmap" "wireshark" "hashcat" "gobuster")

  for item in "${items[@]}"; do
    if has_cmd "$item" 2>/dev/null; then
      printf "  ${GREEN}✔${RESET} %-20s" "$item"
    else
      printf "  ${YELLOW}~${RESET} %-20s" "$item (check manually)"
    fi
  done
  echo ""
  echo ""
  echo -e "${BOLD}${YELLOW}Next steps:${RESET}"
  echo -e "  1. ${CYAN}Log out and back in${RESET} (or 'exec zsh') for shell changes"
  echo -e "  2. ${CYAN}newgrp docker${RESET} to use Docker without sudo immediately"
  echo -e "  3. Add SSH key to GitHub: ${CYAN}cat ~/.ssh/id_ed25519.pub${RESET}"
  echo -e "  4. Run ${CYAN}ibus-setup${RESET} to configure Bangla input"
  echo -e "  5. Full log: ${CYAN}${LOG_FILE}${RESET}"
  echo ""
}

# =============================================================================
# MAIN ENTRYPOINT
# =============================================================================
main() {
  # Initialise log
  mkdir -p "$(dirname "$LOG_FILE")"
  echo "devsetup.sh started at $(date)" > "$LOG_FILE"

  parse_args "$@"
  check_root
  detect_os

  # ── Interactive mode overrides ───────────────────────────────────────────
  $DO_INTERACTIVE && interactive_mode

  # ── Resolve install flags ────────────────────────────────────────────────
  # --full implies everything
  if $DO_FULL; then
    DO_MINIMAL=true; DO_DEVOPS=true; DO_SECURITY=true; DO_GUI=true
    INSTALL_LANGS=true; INSTALL_SHELL=true; INSTALL_CLI=true
    INSTALL_IBUS=true; INSTALL_FLATPAK=true
  fi
  # --minimal baseline
  if $DO_MINIMAL; then
    INSTALL_LANGS="${INSTALL_LANGS:-true}"
    INSTALL_SHELL="${INSTALL_SHELL:-true}"
    INSTALL_CLI="${INSTALL_CLI:-true}"
  fi
  # --devops adds languages + devops
  if $DO_DEVOPS; then
    INSTALL_LANGS="${INSTALL_LANGS:-true}"
    INSTALL_SHELL="${INSTALL_SHELL:-true}"
    INSTALL_CLI="${INSTALL_CLI:-true}"
  fi

  # Defaults (if nothing set, do core at minimum)
  INSTALL_LANGS="${INSTALL_LANGS:-false}"
  INSTALL_SHELL="${INSTALL_SHELL:-false}"
  INSTALL_CLI="${INSTALL_CLI:-false}"
  INSTALL_IBUS="${INSTALL_IBUS:-false}"
  INSTALL_FLATPAK="${INSTALL_FLATPAK:-false}"

  # ── Run stages ─────────────────────────────────────────────────────────
  update_system
  install_core
  install_networking

  $INSTALL_LANGS   && install_languages
  $INSTALL_SHELL   && install_shell
  $INSTALL_CLI     && install_cli_tools

  configure_git
  setup_ssh

  $DO_MINIMAL || $DO_FULL || $DO_DEVOPS || $DO_SECURITY && install_editors
  $DO_DEVOPS   && install_devops
  $DO_SECURITY && install_security
  $DO_GUI      && install_gui_apps
  $INSTALL_IBUS    && install_ibus
  $INSTALL_FLATPAK && install_flatpak

  [[ -n "$DOTFILES_REPO" ]] && setup_dotfiles

  print_summary
}

main "$@"
